_target_: graspsampling.hands.PandaGripper

contact_points:
  - link_name: panda_leftfinger
  - link_name: panda_rightfinger

physics_parameters:
  file_name: "urdf/franka_description/robots/franka_panda_gripper_spherical_dof_acronym.urdf"
  default_config: [0, 0, 0, 0, 0, 0, 0.04, 0.04]
  options:
    flip_visual_attachments: True
  dof_properties:
    driveMode: [1, 1, 1, 1, 1, 1, 2, 2]
    stiffness: [1e3, 1e3, 1e3, 1e3, 1e3, 1e3, 0, 0]
    damping: [50, 50, 50, 50, 50, 50, 800, 800]
    effort: 1400.0
  policy:
    closing_velocity: []
    gripper_type: [panda_hand]
    shake_rot_axis: [0, 1, 0]

width: 0.10537486
depth: 0.10527314
transform_offset_from_asset_to_graspgen_convention: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]] # expressed as translation and quaternion[[xyz],[xyzw]]
symmetric_antipodal: True