data:
    root_dir: ''
    cache_dir: '/tmp/graspgen_train_cache/'
    tasks: ['pick']
    num_points: 16384
    num_object_points: 1024
    cam_coord: False
    num_rotations: 64
    grid_resolution: 0.01
    jitter_scale: 0.
    contact_radius: 0.005
    dist_above_table: 0.002
    robot_prob: 1.0
    offset_bins: [
        0, 0.00794435329, 0.0158887021, 0.0238330509,
        0.0317773996, 0.0397217484, 0.0476660972,
        0.055610446, 0.0635547948, 0.0714991435, 0.08
    ]
    random_seed: -1
    rotation_augmentation: False
    add_depth_noise: False
    downsample_points: True
    downsample_to_fixed_batch_size: False
    dataset_cls: 'PickPlaceDataset'
    load_patch: False
    load_discriminator_dataset: False # True for GraspGenDiscriminator
    patch_width: 256
    prob_point_cloud : -1
    object_root_dir : ''
    grasp_root_dir : ''
    dataset_name : 'acronym'
    dataset_version : 'v1'
    gripper_name: 'franka_panda' # TODO: Define this just in one place.
    num_grasps_per_object: -1
    load_contact: False
    prefiltering: False
    discriminator_ratio: [0.50, 0.20, 0.25, 0.05, 0.0] # [0.40, 0.35, 0.15, 0.05, 0.05]
    visualize_batch: False # visualize the batch datapoint during training
    onpolicy_dataset_dir: null
    onpolicy_dataset_h5_path: null
    redundancy: 1
    preload_dataset: True

m2t2:
    scene_encoder:
        type: 'pointnet2_msg'
        num_points: 16384
        downsample: 4
        radius: 0.02
        radius_mult: 2
        use_rgb: False

    object_encoder:
        type: 'pointnet2_msg_cls'
        num_points: 1024
        downsample: 4
        radius: 0.02
        radius_mult: 2
        use_rgb: False

    contact_decoder:
        mask_feature: 'res0'
        in_features: ['res1', 'res2', 'res3']
        place_feature: 'res4'
        embed_dim: 256
        feedforward_dim: 512
        num_scales: 3
        num_layers: 3
        num_heads: 8
        num_grasp_queries: 100
        num_place_queries: 0
        use_attn_mask: True
        use_task_embed: False
        activation: 'GELU'
        pos_enc: 'new'

    action_decoder:
        use_embed: False
        conf_thresh: 0.5
        max_num_pred: null
        hidden_dim: 256
        num_layers: 2
        activation: 'GELU'
        offset_bins: [
            0, 0.00794435329, 0.0158887021, 0.0238330509,
            0.0317773996, 0.0397217484, 0.0476660972,
            0.055610446, 0.0635547948, 0.0714991435, 0.08
        ] # DEPRECATED
        gripper_depth: 0.1034 # 0.075 for suction
        gripper_name: 'franka_panda'

    matcher:
        object_weight: 2.0
        bce_weight: 5.0
        dice_weight: 5.0

    grasp_loss:
        object_weight: 2.0
        not_object_weight: 0.1
        pseudo_ce_weight: 0.0
        bce_topk: 512
        bce_weight: 5.0
        dice_weight: 5.0
        deep_supervision: True
        recompute_indices: True
        adds_pred2gt: 100.0
        adds_gt2pred: 0.0
        adds_per_obj: False
        contact_dir: 0.0
        approach_dir: 0.0
        offset: 1.0
        offset_bin_weights: [
            0.16652107, 0.21488856, 0.37031708, 0.55618503, 0.75124664,
            0.93943357, 1.07824539, 1.19423112, 1.55731375, 3.17161779
        ] # DEPRECATED
        gripper_name: 'franka_panda'

    place_loss:
        bce_topk: 1024
        bce_weight: 5.0
        dice_weight: 5.0
        deep_supervision: True

diffusion:
    obs_backbone: 'pointnet'
    checkpoint_object_encoder_pretrained: null
    num_embed_dim: 256
    num_obs_dim: 512
    diffusion_embed_dim: 512
    image_size: 256
    num_diffusion_iters: 100
    num_diffusion_iters_eval: 100
    compositional_schedular: True
    loss_pointmatching: True
    loss_l1_pos: False
    loss_l1_rot: False
    grasp_repr: 'r3_6d'
    kappa: -1
    clip_sample: True
    beta_schedule: 'squaredcos_cap_v2'
    npn_architecture: 'ffn'
    attention: 'cat'
    gripper_name: 'franka_panda'
    pose_repr: 'mlp'
    num_grasps_per_object: 100 # Only used during eval
    ptv3:
        grid_size: 0.01 # Only relevant for PTv3 backbone

discriminator:
    checkpoint: null
    checkpoint_object_encoder_pretrained: null
    obs_backbone: 'pointnet'
    num_embed_dim: 256
    num_obs_dim: 512
    grasp_repr: 'r3_6d'
    pose_repr: 'mlp'
    topk_ratio: 0.75
    kappa: 1.0
    gripper_name: 'franka_panda'
    ptv3:
        grid_size: 0.01 # Only relevant for PTv3 backbone

optimizer:
    type: 'ADAMW'
    base_batch_size: 128 # DEPRECATED
    base_lr: 0.0008 # DEPRECATED
    backbone_multiplier: 1.0 # DEPRECATED
    grad_clip: -1 # DEPRECATED
    weight_decay: 0.05
    lr_scale_multiplier: 1.0 # DEPRECATED
    lr: 0.00005
    momentum: 0.9

train:
    model_name: 'm2t2'
    num_gpus: 1
    port: '1234'
    mask_thresh: 0.5
    batch_size: 8
    num_workers: 8
    num_epochs: 160
    print_freq: 25
    plot_freq: 50
    save_freq: 10
    eval_freq: 5
    checkpoint: null
    log_dir: ''
    num_scenes: null
    debug: False
    debug_ddp: False

eval:
    model_name: 'm2t2' # Choose from [m2t2, diffusion, discriminator]
    task: 'pick'
    split: 'valid'
    first_scene: -1
    last_scene: 1000
    scene: null
    acronym_dir: ''
    checkpoint: ''
    output_dir: null
    exp_name: null
    cam_coord: False
    object_thresh: 0.2
    mask_thresh: 0.2
    seed_thresh: null
    num_seed_grasps: 150
    max_num_grasps: 200
    retract: 0.
    grid_res: 0.01
    placement_height: 0.02
    placement_vis_radius: 0.2
    batch_size: 4
    num_workers: 1
    print_freq: 1
    num_procs: 1
    num_vis: 5
    num_runs: 1
    debug: False
    scene_file: ""
    output_file: ""
    write_output_file: True
    grasp_seeder: False
    config_save_file: "/code/FoundationGrasp/configtest.yaml"
    color_grasp_with_conf: False

meshcat:
    visualize: True
    point_size: 0.01
    line_width: 2

obj:
    scale: 1.0
    num_sample_points: 2024

